#!/usr/bin/env bash
set -o errexit
set -o pipefail
set -o nounset
[[ ${DEBUG:-} == true ]] && set -o xtrace

readonly __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

docker_version=$(cat "${__dir}"/../VERSION)
docker build --build-arg PCF_CLI_VERSION="${docker_version}" -f "${DOCKERFILE_PATH}" -t "${IMAGE_NAME}" .
